### ISSUE TITLE
CONDA_PREFIX?

### ISSUE THREAD

**Issue by benman1** [QuantStack/xtensor-benchmark#7]
Hi
I executed the conda install (`conda env create -f environment.yml
`), but cmake is not picking up eigen, armadillo, etc.

```
          COMPILING WITH
======================================


COMPILER        : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
FLAGS           :  -Ofast -ffast-math -march=native -std=c++14 -pthread

Found xtensor   : /Users/ben/anaconda3/include
Found xsimd     : /Users/ben/anaconda3/include


-- Configuring done
-- Generating done

```

In the cmake_install.cmake file I see the conda environment correctly recognised: 

```
# Install script for directory: /Users/ben/xtensor-benchmark

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/Users/ben/anaconda3/envs/xtensor-benchmark")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")
```

Pointers appreciated. Thank you!

**Comment by floatdrop** [comment]
Check these options:

https://github.com/QuantStack/xtensor-benchmark/blob/8bc9d658cb77b6c3e5a59dcafa35f97aeff05c0b/CMakeLists.txt#L88-L92

Pass corresponding options to cmake to test against them.

**Comment by wolfv** [comment]
Thanks @floatdrop, sorry @benman1 for not replying for so long. 

It's correct, you need to manually enable testing against these libraries now (you can also use the ccmake tool if you have it).
